"""Backward-compatible public surface for the Leos agent runtime.

The runtime is split across focused modules. Importing from `leos_agent.core`
continues to work for existing callers.
"""

from __future__ import annotations

from .audit import AuditEvent, AuditLog
from .causal import (
    ActionConsequence,
    CausalEffect,
    CausalGraph,
    CausalHypothesis,
    CausalWorldModel,
    CounterfactualReport,
    CounterfactualReview,
    EffectPrediction,
)
from .causal_contract import CausalContract, safe_file_write_causal_contract
from .conflicts import Conflict, ConflictDetector, ConflictResolutionPolicy
from .dev_tools import (
    GitDiffTool,
    ListFilesTool,
    PatchFileTool,
    ReadFileTool,
    RunTestsTool,
    default_dev_registry,
)
from .enums import (
    CompensationStrategy,
    Decision,
    GoalStatus,
    Permission,
    Reversibility,
    RiskLevel,
    StepStatus,
    TaskStatus,
)
from .errors import (
    BudgetExceeded,
    DryRunFailed,
    IdempotencyConflict,
    InvalidGoalTransition,
    LeosError,
    PolicyConfigurationError,
    PolicyDenied,
    PolicyIntegrityError,
    PostconditionFailed,
    PreconditionFailed,
    RollbackFailed,
    SchemaValidationFailed,
    SecretBoundaryViolation,
    SecretLeakedToUntrustedTool,
    ToolTimeout,
    VerificationFailed,
    WorkspaceEscapeBlocked,
)
from .eval_runner import EvalReport, format_eval_report, render_eval_report_markdown, run_safety_evals
from .goals import Goal, ResourceBudget
from .kernel import AgentKernel
from .manifest import (
    ToolManifest,
    load_tool_manifest_file,
    tool_manifest_from_mapping,
    validate_json_schema,
    validate_tool_manifest,
)
from .memory import MemoryRecord, MemorySensitivity, MemoryStore, MemoryType
from .model import (  # noqa: F401
    FakeModelClient,
    ModelCallError,
    ModelClient,
    ModelRequest,
    ModelResponse,
    ModelUsage,
    StructuredOutputError,
)
from .network_tools import BrowserReadTool, NetworkFetcher, NetworkFetchResponse, NetworkFetchTool, URLSafetyPolicy
from .planner import (  # noqa: F401
    LLMPlannerAdapter,
    Planner,
    StructuredLLMPlanner,
    validate_llm_proposals,
)
from .plans import (
    ActionStep,
    PlanCandidate,
    PlannerConfig,
    PlannerResult,
    PlanProposal,
    PlanScore,
    StateCondition,
    TransactionPlan,
)
from .policy import (
    BUILT_IN_POLICY_PROFILES,
    ApprovalGate,
    ApprovalRequest,
    CapabilityGrant,
    PolicyEngine,
    PolicyProfile,
    PolicyRule,
    build_approval_request,
    validate_policy_config,
)
from .policy_manifest import (
    SignedPolicyManifest,
    load_policy_from_file,
    manifest_to_json,
    sign_policy,
    verify_policy_manifest,
)
from .prompts import (  # noqa: F401
    DEFAULT_PROMPT_REGISTRY,
    PromptRegistry,
    PromptTemplate,
)
from .proof import ProofManifest, exit_code_for_manifest, generate_proofs
from .replay import AuditReplayer, ReplayResult, replay_audit_log
from .sandbox import (  # noqa: F401
    ContainerSandboxRunner,
    DockerSandboxRunner,
    MicroVMSandboxRunner,
    SandboxCommand,
    SandboxCommandTool,
    SandboxResult,
    SandboxRunner,
    SandboxUnavailable,
    WorkspaceSubprocessSandboxRunner,
)
from .simulation import (
    FakeBrowser,
    FakeCalendar,
    FakeEmailServer,
    FakeFileSystem,
    FakeGitHubRepo,
    FakePaymentSystem,
    FakeShell,
    SimulationEnvironment,
)
from .state import TrustLevel, WorldState
from .task_queue import (
    RetryPolicy,
    RuntimeTask,
    TaskQueue,
    TaskRunner,
    TimeoutPolicy,
    Watchdog,
)
from .tools import (
    EchoTool,
    SafeFileWriteTool,
    Secret,
    Tool,
    ToolRegistry,
    ToolResult,
    ToolSpec,
    default_registry,
)
from .trace_viewer import render_trace_html, render_trace_markdown
from .transactions import TransactionManager

__all__ = [
    "ActionConsequence",
    "ActionStep",
    "AgentKernel",
    "ApprovalGate",
    "ApprovalRequest",
    "AuditEvent",
    "AuditLog",
    "AuditReplayer",
    "BUILT_IN_POLICY_PROFILES",
    "BrowserReadTool",
    "BudgetExceeded",
    "CapabilityGrant",
    "CausalContract",
    "CausalEffect",
    "CausalGraph",
    "CausalHypothesis",
    "CausalWorldModel",
    "CausalContract",
    "CompensationStrategy",
    "Conflict",
    "ConflictDetector",
    "ConflictResolutionPolicy",
    "CounterfactualReport",
    "CounterfactualReview",
    "Decision",
    "DryRunFailed",
    "DockerSandboxRunner",
    "EchoTool",
    "EffectPrediction",
    "EvalReport",
    "FakeBrowser",
    "FakeCalendar",
    "FakeEmailServer",
    "FakeFileSystem",
    "FakeGitHubRepo",
    "FakePaymentSystem",
    "FakeShell",
    "GitDiffTool",
    "Goal",
    "GoalStatus",
    "IdempotencyConflict",
    "InvalidGoalTransition",
    "LeosError",
    "ListFilesTool",
    "MemoryRecord",
    "MemorySensitivity",
    "MemoryStore",
    "MemoryType",
    "NetworkFetcher",
    "NetworkFetchResponse",
    "NetworkFetchTool",
    "PatchFileTool",
    "Permission",
    "PlanCandidate",
    "PlanProposal",
    "PlanScore",
    "PatchFileTool",
    "Planner",
    "PlannerConfig",
    "PlannerResult",
    "PolicyConfigurationError",
    "PolicyDenied",
    "PolicyEngine",
    "PolicyIntegrityError",
    "PolicyProfile",
    "PolicyRule",
    "ProofManifest",
    "PostconditionFailed",
    "PreconditionFailed",
    "ProofCommandResult",
    "ProofManifest",
    "Reversibility",
    "RiskLevel",
    "ReplayResult",
    "ResourceBudget",
    "ReadFileTool",
    "RetryPolicy",
    "RollbackFailed",
    "RuntimeTask",
    "RunTestsTool",
    "SafeFileWriteTool",
    "SchemaValidationFailed",
    "Secret",
    "SecretBoundaryViolation",
    "Secret",
    "SecretLeakedToUntrustedTool",
    "SimulationEnvironment",
    "SignedPolicyManifest",
    "ReadFileTool",
    "StateCondition",
    "StepStatus",
    "TaskQueue",
    "TaskRunner",
    "TaskStatus",
    "Tool",
    "ToolManifest",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "ToolTimeout",
    "URLSafetyPolicy",
    "TransactionManager",
    "TransactionPlan",
    "TrustLevel",
    "TimeoutPolicy",
    "VerificationFailed",
    "WorkspaceEscapeBlocked",
    "WorldState",
    "Watchdog",
    "default_dev_registry",
    "default_registry",
    "default_dev_registry",
    "build_approval_request",
    "exit_code_for_manifest",
    "format_eval_report",
    "generate_proofs",
    "load_policy_from_file",
    "load_tool_manifest_file",
    "manifest_to_json",
    "replay_audit_log",
    "render_eval_report_markdown",
    "render_trace_html",
    "render_trace_markdown",
    "run_safety_evals",
    "safe_file_write_causal_contract",
    "sign_policy",
    "safe_file_write_causal_contract",
    "validate_policy_config",
    "validate_json_schema",
    "tool_manifest_from_mapping",
    "validate_tool_manifest",
    "verify_policy_manifest",
]
